default:
  image: reg.agarg.me/build/golang:latest-1.18.2-bullseye
  tags:
    - agarg-public-projects

stages:
  - pre-flight
  - testing

go-fmt-vet:
  stage: pre-flight
  before_script:
    - go get
    - go mod vendor
  script:
    - fmt_output=$(find -name vendor -prune -o -type f -name '*.go' -print0 | xargs -0 gofmt -l)
    - echo "${fmt_output}"
    - test -z "${fmt_output}"
    - go vet ./...
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/

go-test-cover:
  stage: testing
  script:
    - go test -cover -coverprofile cover.out ./...
    - go tool cover -func cover.out | awk '/total:/ {print $1" "$2" "$3}; /.go/{print $0}'
  dependencies:
    - go-fmt-vet
