default:
  image: img.doom.fm/build/golang:latest-1.14.2-buster
  tags:
    - schism-ci-cd

stages:
  - pre-flight
  - testing

go-fmt-vet:
  stage: pre-flight
  before_script:
    - go mod vendor
  script:
    - go fmt ./...
    - go vet ./...
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/

go-test-cover:
  stage: testing
  script:
    - go test -cover -coverprofile cover.out ./...
    - go tool cover -func cover.out | awk '/total:/ {print $1" "$2" "$3}; /.go/{print $0}'
  dependencies:
    - go-fmt-vet
